### ISSUE TITLE
开启celery报错

### ISSUE THREAD

**Issue by miaolaoda007** [TencentBlueKing/bamboo-engine#66]
$ DJANGO_SETTINGS_MODULE=bamboo_engine_playground.settings celery worker -A bamboo_engine_playground.settings -Q er_execute,er_schedule -l info
到这一步报错，ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [WinError 10061] 由于目标计算机积极拒绝，无法连接。.
Trying again in 8.00 seconds... (4/100)
Traceback (most recent call last):
  File "d:\program files\python37\lib\site-packages\pipeline\component_framework\base.py", line 88, in __new__
    code=new_class.code, version=new_class.version, defaults={"name": new_name, "status": __debug__}
  File "d:\program files\python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "d:\program files\python37\lib\site-packages\django\db\models\query.py", line 564, in update_or_create
    obj.save(using=self.db)
  File "d:\program files\python37\lib\site-packages\django\db\models\base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "d:\program files\python37\lib\site-packages\django\db\models\base.py", line 782, in save_base
    force_update, using, update_fields,
  File "d:\program files\python37\lib\site-packages\django\db\models\base.py", line 854, in _save_table
    forced_update)
  File "d:\program files\python37\lib\site-packages\django\db\models\base.py", line 903, in _do_update
    return filtered._update(values) > 0
  File "d:\program files\python37\lib\site-packages\django\db\models\query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "d:\program files\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "d:\program files\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "d:\program files\python37\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "d:\program files\python37\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "d:\program files\python37\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "d:\program files\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "d:\program files\python37\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "d:\program files\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "d:\program files\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
update pipe_example_component component model
update component models
ERROR:root:database is locked

**Comment by miaolaoda007** [comment]
13

**Comment by miaolaoda007** [comment]
123
